//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJwelaryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int feedback_id { get; set; }
        public string user_id { get; set; }
        public string feedback1 { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
