//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJwelaryShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineShopEntities9 : DbContext
    {
        public OnlineShopEntities9()
            : base("name=OnlineShopEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<Carttrac> Carttracs { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<history> histories { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Order_details> Order_details { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<sub_category> sub_category { get; set; }
    }
}
